---
run:
  timeout: 3m
  build-tags:
    - integration

linters:
  enable:
    - misspell
    - goimports
    - revive
    - gofmt
    - depguard
    - godot
issues:
  exclude-rules:
    # `go run` doesn't set the VCS version.
    - path: cmd/simple-ingress-external-auth/simple-ingress-external-auth.go
      text: "error obtaining VCS status"
